apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-pipeline-runs
spec:
  params:
    - name: namespace
      type: string
      description: The namespace to clean up the pipeline runs
    - name: days
      type: string
      description: Number of days after which pipeline runs should be deleted
  steps:
    - name: cleanup
      image: bitnami/kubectl:latest
      script: |
        #!/bin/bash
        kubectl delete pipelineruns -n $(params.namespace) --field-selector=status.startTime<=$(date -d "-$(params.days) days" +%Y-%m-%dT%H:%M:%SZ)
